# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

udp_load_model <- function(file_model) {
    .Call('_udpipe_udp_load_model', PACKAGE = 'udpipe', file_model)
}

udp_tokenise_tag_parse <- function(udmodel, x, docid, annotation_tokenizer, annotation_tagger, annotation_parser) {
    .Call('_udpipe_udp_tokenise_tag_parse', PACKAGE = 'udpipe', udmodel, x, docid, annotation_tokenizer, annotation_tagger, annotation_parser)
}

na_locf <- function(x) {
    .Call('_udpipe_na_locf', PACKAGE = 'udpipe', x)
}

udp_train <- function(model_file, conllu_input_files, conllu_heldout_files, annotation_tokenizer, annotation_tagger, annotation_parser) {
    .Call('_udpipe_udp_train', PACKAGE = 'udpipe', model_file, conllu_input_files, conllu_heldout_files, annotation_tokenizer, annotation_tagger, annotation_parser)
}

